name: '${name}'
version: '${version}'
description: '${description}'
api-version: 1.12
main: my.telir.stonesimulator.Main

commands:
  level:
    aliases: [ l ]
    usage: /level [player]
    description: Show player level and xp
  playtime:
    aliases: [ pt ]
    usage: /playtime [player]
    description: Show player playtime